apiVersion: v1
kind: Pod
metadata:
  name: liveness-http
  labels:
    app: web
spec:
  containers:
  - name: liveness
    image:  k8s.gcr.io/liveness
    args: ["/server"]
    resources:
    ports:
      - containerPort: 8080
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
        httpHeaders:
        - name: Custom-Header
          value: Awesome
      initialDelaySeconds: 3
      periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: liveness-service
spec:
  type: NodePort
  selector:
    app: web
  ports:
  - port: 8080
    targetPort: 8080
