apiVersion: apps/v1
kind: Deployment
metadata:
  name: myweb-deployment
spec:
  selector:
    matchLabels:
      app: web
  replicas: 1
  template:
    metadata:
      name: "python-web"
      labels:
        app: web
    spec:
      containers:
      - name: python
        image: python:2.7
        resources: 
          limits:
            memory: "128Mi"
            cpu: "500m"        
        command: ["/bin/bash"]
        args: ["-c", "echo \"<p>Hello from $(hostname)</p>\" > index.html; sleep 30; python -m SimpleHTTPServer 8080"]
        ports:
        - name: http
          containerPort: 8080
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: myweb-service
spec:
  type: NodePort
  selector:
    app: web
  ports:
  - port: 8080
    targetPort: 8080