apiVersion: v1
kind: Pod
metadata:
  name: python-web
  labels:
    app: web
spec:
  containers:
  - name: python
    image: python:2.7
    command: ["/bin/bash"]
    args: ["-c", "echo \"<p>Hello from $(hostname)</p>\" > index.html; sleep 10; python -m SimpleHTTPServer 8080"]
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
    readinessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 10
      periodSeconds: 10